updated readme addressing reviewer comments
diskin-lab-chop/AutoGVP pull request #213
Opened 2024-01-22 16:59 UTC by naqvia

Addressing the following reviewer comments:

> 8. I also have some suggestions on GitHub: 1) In README.md, add software dependencies (for example, VEP, ANNOVAR, InterVar, AutoPVS1, vt, Bcftools); add where to get variant_summary.txt.gz and submission_summary.txt.gz before using them in select-clinVar-submissions.R, otherwise users will confuse when reading “Custom workflow example run”, until find what are they in FAQ; 2) In User-Guide, it would be great to add code of running AutoPVS1. It’s okay not to add if it is too complicated.

2024-01-22 17:02 UTC, naqvia commented
@jungkim2 Can you add the code for running AutoPVS1 in the User-guide?

2024-01-22 18:58 UTC, jungkim2 requested changes
I have modified WIKI user guide adding code to run AutoPVS1.

2024-01-22 18:58 UTC, jungkim2 commented on README.md
> +2. Download [database files](https://github.com/diskin-lab-chop/AutoGVP/blob/main/scripts/download_db_files.sh) and run `select-clinVar-submissions.R` with desired conflict resolution parameter ("lat
isn't conflict resoluation parameter only required when ClinGen ConceptID list is provided?

2024-01-22 18:58 UTC, jungkim2 commented on README.md
for ClinVar VCF, it is now an option for CAVATICA workflow right? 
should we be explicit about that? 

required for custom workflow and optional for CATATICA?

2024-02-01 15:44 UTC, jungkim2 approved these changes

2024-02-01 16:43 UTC, merged