cavatica workflow test run
diskin-lab-chop/AutoGVP pull request #34
Opened 2023-06-26 22:23 UTC by naqvia

Testing on sample data from CAVATICA pre-processed output files from workflow. This includes: 
```

- test files generation
- gnomad filtering
- ensure that script runs and outputs desired files

```

2023-06-26 22:32 UTC, naqvia commented
I still need to upload test files and update readme, but the script now runs-- here is a sample command run: 
`Rscript 01-annotate_variants_CAVATICA_input.R --vcf input/test-cavatica.single.vqsr.filtered.vep_105.vcf --intervar input/test-cavatica.hg38_multianno.txt.intervar --multianno input/test-cavatica.hg38_multianno.txt --variant_summary input/variant_summary.txt --submission_summary input/submission_summary.txt --autopvs1 input/test-cavatica.autopvs1.tsv`

Some of the variables were not updated which were causing it to crash. May be of interest to have a "check" to see if input files and variables are in correct format or some simple QC step like that since the scripts are super sensitive to format.

2023-06-27 14:11 UTC, naqvia commented
Added : ` mutate(gnomad_af     = if_else( as.numeric( str_match(INFO, gnomad_var_to_match)[,2])  > filter_variant_af, "PASS","FAIL")) ` , which will take in any user-inputted gnomad variable and threshold.

2023-06-27 14:43 UTC, naqvia commented
this PR should address https://github.com/diskin-lab-chop/AutoGVP/issues/32 https://github.com/diskin-lab-chop/AutoGVP/issues/24 and https://github.com/diskin-lab-chop/AutoGVP/issues/17

2023-06-27 21:32 UTC, rjcorb requested changes
input vcf variable file needs changing (see suggestion), otherwise runs fine.

2023-06-27 21:32 UTC, rjcorb commented on AutoGVP/01-annotate_variants_CAVATICA_input.R
> +vcf_input <-  vroom("/Users/naqvia/Documents/GitHub/pathogenicity-assessment/AutoGVP/input/test-cavatica.single.vqsr.filtered.vep_105.vcf", comment = "#",delim="\t", col_names = c("CHROM","START","ID
```suggestion
vcf_input <-  vroom(input_clinVar_file, comment = "#",delim="\t", col_names = c("CHROM","START","ID","REF","ALT","QUAL","FILTER","INFO","FORMAT","Sample"), show_col_types = TRUE)
```

2023-06-29 20:31 UTC, merged