removed variants from intervar run that got a call from submission files
diskin-lab-chop/AutoGVP pull request #72
Opened 2023-07-14 14:57 UTC by naqvia

Related to https://github.com/diskin-lab-chop/AutoGVP/issues/50

2023-07-16 23:13 UTC, jharenza requested changes
Untested, but left code change comments. I'm also going to work with Chris to implement the R styler package on this code so it adheres to tidyverse guidelines and is more readable. Stay tuned!

2023-07-16 23:13 UTC, jharenza commented on AutoGVP/01-annotate_variants_custom_input.R
> +clinvar_anno_vcf_df  <- vroom("/Users/naqvia/Documents/GitHub/pathogenicity-assessment/AutoGVP/input/clinvar.vcf.gz", comment = "#", delim="\t", col_names = c("CHROM","POS","ID","REF","ALT","QUAL","F
Please fix this path

2023-07-16 23:13 UTC, jharenza commented on AutoGVP/01-annotate_variants_custom_input.R
> +                                ungroup
```suggestion
                                ungroup()
```

2023-07-16 23:13 UTC, jharenza commented on AutoGVP/01-annotate_variants_custom_input.R
> +                          ungroup
```suggestion
                          ungroup()
```

2023-07-16 23:13 UTC, jharenza commented on AutoGVP/01-annotate_variants_custom_input.R
> +entries_for_intervar <- filter(clinvar_anno_vcf_df, Stars == "0", na.rm = TRUE) %>% bind_rows((additional_intervar_cases)) %>% bind_rows(clinvar_anti_join_vcf_df) #%>% anti_join(entries_for_cc_in_sub
Remove commented text

2023-07-16 23:13 UTC, jharenza commented on AutoGVP/01-annotate_variants_custom_input.R
> +  #dplyr::filter(vcf_id %in% clinvar_anno_intervar_vcf_df$vcf_id)
Delete this

2023-07-17 22:06 UTC, jungkim2 approved these changes
tested the code, it solved duplicated variant output. But other issues have been identified. submitting separate issues for those.

2023-07-17 22:53 UTC, naqvia commented
Current issue has been fixed. There are other issues that @jungkim2 will write an issue for!

2023-07-18 13:57 UTC, jungkim2 approved these changes

2023-07-18 14:21 UTC, naqvia commented
latest commit is related to https://github.com/diskin-lab-chop/AutoGVP/issues/76

2023-07-19 20:03 UTC, merged